spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  config:
    import: file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
aws:
  access: ${AWS_ACCESS}
  secret: ${AWS_SECRET}
