spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  config:
    import: file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${SECRET_KEY}

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

aws:
  access: ${AWS_PUBLIC}
  secret: ${AWS_SECRET}

logging:
  level:
    org.springframework.security.web.csrf: debug
